//----- SHADER DEFINES -----
#define MAX_BONES 100
#define MIN_AMBIENT_LIGHT 0.3

//----- UNIFORM LOCATION -----
#define PVM_UNIFORM_LOCATION 100
#define VM_UNIFORM_LOCATION 101
#define VP_UNIFORM_LOCATION 102
#define TIM_UNIFORM_LOCATION 103
#define M_UNIFORM_LOCATION 104
#define V_UNIFORM_LOCATION 105
#define P_UNIFORM_LOCATION 106

#define BONES_LOCATION 200

#define AMBIENT_COLOR_UNIFORM_LOCATION 300
#define COLOR_UNIFORM_LOCATION 301
#define DIFFUSE_COLOR_UNIFORM_LOCATION 302
#define SCREEN_DIMENSIONS_UNIFORM_LOCATION 303
#define FILL_COLOR_UNIFORM_LOCATION 304
#define FILL_PERCENTAGE_UNIFORM_LOCATION 305
#define GLOW_INTENSITY_UNIFORM_LOCATION 306
#define CAMERA_POSITION_UNIFORM_LOCATION 306
#define SSAO_QUALITY_UNIFORM_LOCATION 308

#define LOCAL_UNIFORM_LOCATION1;

//----- TEXTURE LOCATION -----
#define SSAO_TEXTURE_LOCATION 0
#define SHADOW_TEXTURE_LOCATION 1
#define LOCAL_TEXTURE_LOCATION1 2
#define LOCAL_TEXTURE_LOCATION2 3
#define LOCAL_TEXTURE_LOCATION3 4
#define LOCAL_TEXTURE_LOCATION4 5
#define LOCAL_TEXTURE_LOCATION5 6
#define LOCAL_TEXTURE_LOCATION6 7
#define LOCAL_TEXTURE_LOCATION7 8
#define LOCAL_TEXTURE_LOCATION8 9
#define LOCAL_TEXTURE_LOCATION9 10
#define LOCAL_TEXTURE_LOCATION10 11
#define LOCAL_TEXTURE_LOCATION11 12
#define LOCAL_TEXTURE_LOCATION12 13
#define LOCAL_TEXTURE_LOCATION13 14
#define LOCAL_TEXTURE_LOCATION14 15
#define LOCAL_TEXTURE_LOCATION15 16
#define LOCAL_TEXTURE_LOCATION16 17
#define LOCAL_TEXTURE_LOCATION17 18
#define LOCAL_TEXTURE_LOCATION18 19
#define LOCAL_TEXTURE_LOCATION19 20
#define LOCAL_TEXTURE_LOCATION20 21
#define LOCAL_TEXTURE_LOCATION21 22
#define LOCAL_TEXTURE_LOCATION22 23
#define LOCAL_TEXTURE_LOCATION23 24
#define LOCAL_TEXTURE_LOCATION24 25
#define LOCAL_TEXTURE_LOCATION25 26
